# Generated by Django 2.1.7 on 2019-03-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_hotelchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='', max_length=80),
        ),
    ]
