# Generated by Django 2.1.7 on 2019-03-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotel_code', models.CharField(max_length=10)),
                ('hotel', models.CharField(max_length=100)),
                ('rating_type', models.CharField(choices=[('F', 'FTI Rating'), ('O', 'Official Rating')], default='F', max_length=1)),
                ('rating', models.CharField(choices=[('5+', '*****+'), ('5', '*****'), ('4+', '****+'), ('4', '****'), ('3+', '***+'), ('3', '***'), ('2+', '**+'), ('2', '**'), ('1+', '*+'), ('1', '*')], max_length=2)),
                ('i5_code', models.CharField(max_length=10)),
                ('gwg_code', models.CharField(max_length=10)),
                ('giata_code', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.City')),
                ('hotel_chain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.HotelChain')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_code', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=50)),
                ('emails', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.Team'),
        ),
    ]
