# Generated by Django 2.1.7 on 2019-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20190316_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_code',
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='giata_code',
            field=models.CharField(db_index=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='gwg_code',
            field=models.CharField(db_index=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='i5_code',
            field=models.CharField(db_index=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotelchain',
            name='hotel_chain',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelchain',
            name='hotel_chain_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_code',
            field=models.CharField(db_index=True, max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default=True, max_length=10, null=True, unique=True),
        ),
    ]
