# Generated by Django 2.1.7 on 2019-03-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20190318_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('city', 'region__region', 'region__country__country'), 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',), 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('hotel',)},
        ),
        migrations.AlterModelOptions(
            name='hotelchain',
            options={'ordering': ('hotel_chain',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('region', 'country__country')},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('supplier',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('team',)},
        ),
    ]
