# Generated by Django 2.1.7 on 2019-03-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_auto_20190320_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('city',), 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',), 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('hotel',)},
        ),
        migrations.AlterModelOptions(
            name='hotelchain',
            options={'ordering': ('hotel_chain',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('region',)},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('supplier',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('team',)},
        ),
    ]
