# Generated by Django 2.1.7 on 2019-03-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_auto_20190320_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_season',
            field=models.BooleanField(default=True),
        ),
    ]
