# Generated by Django 2.1.7 on 2019-03-24 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_season_current_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract.City'),
            preserve_default=False,
        ),
    ]
